name: Tests

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - BASE_IMAGE_TAG: gcc9-qt513
          - BASE_IMAGE_TAG: gcc9-qt512
          - BASE_IMAGE_TAG: gcc9-qt59
          - BASE_IMAGE_TAG: gcc8-qt513
          - BASE_IMAGE_TAG: gcc8-qt512
          - BASE_IMAGE_TAG: gcc8-qt59
          - BASE_IMAGE_TAG: gcc7-qt513
          - BASE_IMAGE_TAG: gcc7-qt512
          - BASE_IMAGE_TAG: gcc7-qt59
          - BASE_IMAGE_TAG: gcc4.8-qt56
          - BASE_IMAGE_TAG: clang9-qt513
          - BASE_IMAGE_TAG: clang9-qt512
          - BASE_IMAGE_TAG: clang9-qt59
          - BASE_IMAGE_TAG: clang8-qt513
          - BASE_IMAGE_TAG: clang8-qt512
          - BASE_IMAGE_TAG: clang8-qt59
          - BASE_IMAGE_TAG: clang7-qt513
          - BASE_IMAGE_TAG: clang7-qt512
          - BASE_IMAGE_TAG: clang7-qt59

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cat Dockerfile.in | m4 -DBASE_IMAGE_TAG=${{ matrix.BASE_IMAGE_TAG }} > Dockerfile
          docker build . -t test
      - name: Test
        run: docker run --security-opt seccomp=unconfined test

  macos:
    runs-on: macos-10.15
    
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew update
          brew install qt@5
          brew link --force qt@5
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5)
          make package VERBOSE=1 DESTDIR=$(pwd)/install
      - name: Test
        run: make test
        working-directory: build
