name: Tests

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - image: gcc:14
          - image: gcc:15
          - image: silkeh/clang:20
        qt_version: ["6.8", "6.11"]

    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v7

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y libfreetype-dev libfontconfig1-dev libgl1-mesa-dev libpulse-dev libxkbcommon-dev libxcb-xkb-dev pkg-config python3-pip

      - name: Configure pip
        run: |
          python3 -m pip config set global.break-system-packages true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          cache: true
          install-deps: false
          # actions/setup-python is incompatible with silkeh/clang image
          setup-python: false
          tools: 'tools_cmake'
        env:
          PKG_CONFIG_PATH: "/usr/lib/pkgconfig:/usr/share/pkgconfig"

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build \
            --config Release \
            --parallel $(nproc) \
            --verbose

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        qt_version: ["6.8", "6.11"]

    steps:
      - uses: actions/checkout@v7

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          cache: true
          tools: 'tools_cmake'

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build \
            --config Release \
            --parallel $(sysctl -n hw.ncpu) \
            --verbose

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure

      - name: Package
        run: |
          cmake --build build --target package

      - name: Upload DMG
        uses: actions/upload-artifact@v7
        with:
          name: macos-qt-${{ matrix.qt_version }}
          path: build/Fips-*-Darwin.dmg

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_version: ["6.8"]

    steps:
      - uses: actions/checkout@v7

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          cache: true
          tools: 'tools_cmake'

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release --parallel --verbose

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3

      - name: Install WiX
        run: |
          dotnet tool install --global wix
          wix.exe eula accept wix7
          wix.exe extension add --global WixToolset.UI.wixext

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Package
        run: |
          cmake --build build --config Release --target package

      - name: Debug WiX log
        if: failure()
        run: |
          type ./build/_CPack_Packages/win64/WIX/wix.log

      - name: Upload MSI
        uses: actions/upload-artifact@v7
        with:
          name: windows-qt-${{ matrix.qt_version }}
          path: build/Fips-*-win64.msi

  publish:
    needs: [macos, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: macos-qt-6.11

      - uses: actions/download-artifact@v8
        with:
          name: windows-qt-6.8

      - name: Upload artifacts to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: |
            Fips-*-Darwin.dmg
            Fips-*-win64.msi
